logger:
  debug: true           # output debug information
  save: true            # write data to file
  save_path: ""         # default: source_dir/log/<timestamp>.log
driver:
  max_leaner_vel: 0.5   # m/s
tcp_server:
  port: 10000
  timeout: 500          # ms
lidar:
  device_name: "/dev/ttyACM1"
  baudrate: 115200